version: '3.7'
name: "logihub"
services:
  logihub-app:
    image: logihub
    container_name: logihub-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./files:/tmp/reports:rwx
      - ./files:/tmp/images:rwx
    depends_on:
      - logihub-mysql-db
    environment:
      - DATASOURCE_URL=${DATASOURCE_URL}
      - DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    networks:
      - "net"

  logihub-mysql-db:
    image: mysql:latest
    container_name: logihub-mysql-db
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - "net"

networks:
  net:
    driver: bridge